// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sysmon.proto

package sysmon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NullReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullReq) Reset()         { *m = NullReq{} }
func (m *NullReq) String() string { return proto.CompactTextString(m) }
func (*NullReq) ProtoMessage()    {}
func (*NullReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3063dfc0b320e19a, []int{0}
}

func (m *NullReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullReq.Unmarshal(m, b)
}
func (m *NullReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullReq.Marshal(b, m, deterministic)
}
func (m *NullReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullReq.Merge(m, src)
}
func (m *NullReq) XXX_Size() int {
	return xxx_messageInfo_NullReq.Size(m)
}
func (m *NullReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NullReq.DiscardUnknown(m)
}

var xxx_messageInfo_NullReq proto.InternalMessageInfo

type SysMonInfo struct {
	AvgTime              int32    `protobuf:"varint,1,opt,name=avg_time,json=avgTime,proto3" json:"avg_time,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Val                  float64  `protobuf:"fixed64,3,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysMonInfo) Reset()         { *m = SysMonInfo{} }
func (m *SysMonInfo) String() string { return proto.CompactTextString(m) }
func (*SysMonInfo) ProtoMessage()    {}
func (*SysMonInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3063dfc0b320e19a, []int{1}
}

func (m *SysMonInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysMonInfo.Unmarshal(m, b)
}
func (m *SysMonInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysMonInfo.Marshal(b, m, deterministic)
}
func (m *SysMonInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysMonInfo.Merge(m, src)
}
func (m *SysMonInfo) XXX_Size() int {
	return xxx_messageInfo_SysMonInfo.Size(m)
}
func (m *SysMonInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SysMonInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SysMonInfo proto.InternalMessageInfo

func (m *SysMonInfo) GetAvgTime() int32 {
	if m != nil {
		return m.AvgTime
	}
	return 0
}

func (m *SysMonInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysMonInfo) GetVal() float64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto.RegisterType((*NullReq)(nil), "sysmon.NullReq")
	proto.RegisterType((*SysMonInfo)(nil), "sysmon.SysMonInfo")
}

func init() {
	proto.RegisterFile("sysmon.proto", fileDescriptor_3063dfc0b320e19a)
}

var fileDescriptor_3063dfc0b320e19a = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xae, 0x2c, 0xce,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x38, 0xb9, 0xd8,
	0xfd, 0x4a, 0x73, 0x72, 0x82, 0x52, 0x0b, 0x95, 0xbc, 0xb9, 0xb8, 0x82, 0x2b, 0x8b, 0x7d, 0xf3,
	0xf3, 0x3c, 0xf3, 0xd2, 0xf2, 0x85, 0x24, 0xb9, 0x38, 0x12, 0xcb, 0xd2, 0xe3, 0x4b, 0x32, 0x73,
	0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xd8, 0x13, 0xcb, 0xd2, 0x43, 0x32, 0x73, 0x53,
	0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c,
	0x90, 0x48, 0x59, 0x62, 0x8e, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x63, 0x10, 0x88, 0x69, 0xe4, 0xc4,
	0xc5, 0x1d, 0x0c, 0xb6, 0xc1, 0x31, 0x3d, 0x35, 0xaf, 0x44, 0xc8, 0x98, 0x8b, 0xc3, 0x3d, 0xb5,
	0x24, 0xb8, 0x24, 0xb1, 0xa4, 0x58, 0x88, 0x5f, 0x0f, 0xea, 0x12, 0xa8, 0xc5, 0x52, 0x42, 0x30,
	0x01, 0x84, 0xf5, 0x4a, 0x0c, 0x06, 0x8c, 0x4e, 0xea, 0x51, 0xaa, 0xe9, 0x99, 0x25, 0x19, 0xa5,
	0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x29, 0x49, 0x89, 0x45, 0x89, 0x25, 0xa9, 0x95, 0xfa, 0xf9,
	0x25, 0xa5, 0xc5, 0xf1, 0xe9, 0xf9, 0xf1, 0x19, 0xe5, 0xfa, 0x10, 0x7d, 0x49, 0x6c, 0x60, 0x3f,
	0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x6c, 0x33, 0xd0, 0xe3, 0x00, 0x00, 0x00,
}
